source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

target 'Stonks' do
    pod 'SwiftLint'
    pod 'Charts'
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'PinLayout'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
    pod 'Firebase/Analytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
    end
  end
  
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
  end
     
end
